before:
  hooks:
    - go mod tidy
    - go mod verify
    - go mod download

builds:
  - goos:
      - linux
      - windows
      - darwin
      - freebsd

    goarch:
      - amd64
      - arm
      - arm64

    binary: regolancer

    main: main.go

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

archives:
  - name_template: "{{ tolower .ProjectName }}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      freebsd: FreeBSD

    files:
      - LICENSE
      - config.toml.sample
      - config.json.sample

    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

